### ISSUE TITLE
Totem  lua errors

### ISSUE THREAD

**Issue by Twiz777** [caboyd/LunaUnitFrames-ClassicFix#12]
Lots of errors whenever I cast totems, heres the error report.

Message: ...e/AddOns/LunaUnitFrames/libs/oUF/elements/totems.lua:99: bad argument #1 to 'SetValue' (must be a finite number - Usage: self:SetValue(value))
Time: Wed Nov 22 21:09:11 2023
Count: 7039
Stack: ...e/AddOns/LunaUnitFrames/libs/oUF/elements/totems.lua:99: bad argument #1 to 'SetValue' (must be a finite number - Usage: self:SetValue(value))
[string "=[C]"]: in function `SetValue'
[string "@Interface/AddOns/LunaUnitFrames/libs/oUF/elements/totems.lua"]:99: in function <...e/AddOns/LunaUnitFrames/libs/oUF/elements/totems.lua:91>

Locals: (*temporary) = StatusBar {
 0 = <userdata>
 total = 0
 bg = Texture {
 }
}
(*temporary) = Infinite
(*temporary) = "must be a finite number - Usage: self:SetValue(value)"

**Comment by caboyd** [comment]
Quick fix, Turn on auto hide for totem timers.

I will work on actual fix. The game is trying to update the timer but the duration is 0 if there is no totem and the divide by zero causes error.

**Comment by caboyd** [comment]
Try [Release 4357](https://github.com/caboyd/LunaUI-ClassicFix/releases/tag/4357). It should be fixed.

**Comment by Twiz777** [comment]
Got a small new problem. When I place my totems and move to max range to force them to despawn it seems to lock up the timer once I place a new totem. So as an example i'll drop all four totems, move far enough away to force them to despawn, timers go from shown to hidden because I no longer have any totems active and then once I place one totem it'll then show the three unplaced totems with a frozen timer. Sorry if im explaining this poorly, the screenshot shows what it looks like with only a fire totem placed.
![image](https://github.com/caboyd/LunaUI-ClassicFix/assets/151802333/c7658316-32ac-4ddd-89fe-e00029a94914)

**Comment by caboyd** [comment]
I added another check to set the timers to 0 when the totems no longer exist so it should all work now. [Release 4358](https://github.com/caboyd/LunaUI-ClassicFix/releases/tag/4358)
