### ISSUE TITLE
Player 3D Portrait isn't affected by the Combat Fader setting.

### ISSUE THREAD

**Issue by FireReaver** [caboyd/LunaUnitFrames-ClassicFix#15]
Hi, I'm glad you hopped in and started fixing this addon.
I've been using is since many years and my brain can't really play without it anymore.

_**Issue:**_ the Player 3D Portrait isn't affected by the Combat Fader setting.
**_Correct behavior:_** it should be hidden by it, like the other options already do (2D/2D Class/Class)

https://imgur.com/NqNyQ5Y
https://imgur.com/tLjJtAm
https://imgur.com/no83d6S
https://imgur.com/45VT1RP
https://imgur.com/GPdmgBO

Thank you <3

P.S: I'm using the latest version available along with the latest SharedMedia dependency (just to have back the old fonts/statusbars)

**Comment by caboyd** [comment]
I forced the 3d model to fade with everything else.
https://github.com/caboyd/LunaUI-ClassicFix/releases/tag/4359

**Comment by FireReaver** [comment]
Holy, that was fast, thank you!
