### ISSUE TITLE
Luna not being loaded / cannot access config

### ISSUE THREAD

**Issue by Hmmintriguing** [caboyd/LunaUnitFrames-ClassicFix#2]
Hey there,

Thanks a ton for continuing to update Luna to the newest Classic Era patch 1.15.0.

I downloaded it earlier today and tested it on a level 1 character with Luna being the only active addon, and it does not load upon log in, nor am I able to access the Luna config.

I checked BugGrabber and here are both the errors I am receiving whenever I log in or try to type /luna or /lunaunitframes:

1. 1x LunaUnitFrames/modules/layout.lua:506: attempt to index field '?' (a nil value)
[string "@LunaUnitFrames/modules/layout.lua"]:506: in function `styleFunc'
[string "@LunaUnitFrames/libs/oUF/ouf.lua"]:315: in function <LunaUnitFrames/libs/oUF/ouf.lua:250>
[string "=(tail call)"]: ?
[string "@LunaUnitFrames/libs/oUF/ouf.lua"]:704: in function `Spawn'
[string "@LunaUnitFrames/LunaUnitFrames.lua"]:1380: in function `SpawnUnits'
[string "@LunaUnitFrames/LunaUnitFrames.lua"]:251: in function `OnLoad'
[string "@LunaUnitFrames/LunaUnitFrames.lua"]:1625: in function <LunaUnitFrames/LunaUnitFrames.lua:1623>

Locals:
frame = LUFUnitarena {
 0 = <userdata>
 bg = Texture {
 }
 indicators = <table> {
 }
 tags = <table> {
 }
 Power = StatusBar {
 }
 PLAYER_ENTERING_WORLD = <function> defined @LunaUnitFrames/libs/oUF/ouf.lua:184
 Health = StatusBar {
 }
 unit = "arena"
 toplevel = Frame {
 }
 unitEvents = <table> {
 }
 style = "LunaUnitFrames"
 UNIT_PET = <function> defined @LunaUnitFrames/libs/oUF/ouf.lua:224
 modules = <table> {
 }
 Empty = StatusBar {
 }
 __elements = <table> {
 }
 StatusPortrait = <table> {
 }
}
unit = "arena"
notHeaderChild = true
unit = nil
Portrait = <table> {
 texture = Texture {
 }
 model = PlayerModel {
 }
}
Health = StatusBar {
 0 = <userdata>
 name = "Health"
 colorTapping = true
 bg = Texture {
 }
 colorDisconnected = true
 colorCivilian = true
 UpdateColor = <function> defined @LunaUnitFrames/modules/overrides.lua:159
 colorHealth = true
}
Background = Texture {
 0 = <userdata>
}
Power = StatusBar {
 0 = <userdata>
 frequentUpdates = true
 colorDisconnected = true
 colorPower = true
 bg = Texture {
 }
 name = "Power"
}
Background = Texture {
 0 = <userdata>
}
(*temporary) = <function> defined =[C]:-1
(*temporary) = nil
(*temporary) = nil
(*temporary) = LUFUnitarena {
 0 = <userdata>
 bg = Texture {
 }
 indicators = <table> {
 }
 tags = <table> {
 }
 Power = StatusBar {
 }
 PLAYER_ENTERING_WORLD = <function> defined @LunaUnitFrames/libs/oUF/ouf.lua:184
 Health = StatusBar {
 }
 unit = "arena"
 toplevel = Frame {
 }
 unitEvents = <table> {
 }
 style = "LunaUnitFrames"
 UNIT_PET = <function> defined @LunaUnitFrames/libs/oUF/ouf.lua:224
 modules = <table> {
 }
 Empty = StatusBar {
 }
 __elements = <table> {
 }
 StatusPortrait = <table> {
 }
}
(*temporary) = StatusBar {
 0 = <userdata>
 name = "Empty"
}
(*temporary) = nil
(*temporary) = <userdata>
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index field '?' (a nil value)"
UnitSpecific = <table> {
 mainassisttarget = <function> defined @LunaUnitFrames/modules/layout.lua:402
 targettargettarget = <function> defined @LunaUnitFrames/modules/layout.lua:286
 partytarget = <function> defined @LunaUnitFrames/modules/layout.lua:313
 mainassisttargettarget = <function> defined @LunaUnitFrames/modules/layout.lua:406
 party = <function> defined @LunaUnitFrames/modules/layout.lua:290
 maintanktarget = <function> defined @LunaUnitFrames/modules/layout.lua:371
 raidpet = <function> defined @LunaUnitFrames/modules/layout.lua:344
 pettargettarget = <function> defined @LunaUnitFrames/modules/layout.lua:240
 raid = <function> defined @LunaUnitFrames/modules/layout.lua:321
 pet = <function> defined @LunaUnitFrames/modules/layout.lua:217
 partypet = <function> defined @LunaUnitFrames/modules/layout.lua:317
 player = <function> defined @LunaUnitFrames/modules/layout.lua:53
 mainassist = <function> defined @LunaUnitFrames/modules/layout.lua:379
 maintanktargettarget = <function> defined @LunaUnitFrames/modules/layout.lua:375
 targettarget = <function> defined @LunaUnitFrames/modules/layout.lua:282
 maintank = <function> defined @LunaUnitFrames/modules/layout.lua:348
 target = <function> defined @LunaUnitFrames/modules/layout.lua:244
 pettarget = <function> defined @LunaUnitFrames/modules/layout.lua:236
}
backdrop = <table> {
 insets = <table> {
 }
 bgFile = "Interface\Tooltips\UI-Tooltip-Background"
 tileSize = 16
 tile = true
}

2. 1x LunaUnitFrames/modules/options.lua:8891: LunaUnitFrames isn't registed with AceConfigRegistry, unable to open config
[string "=[C]"]: ?
[string "@LunaUnitFrames/libs/AceConfig-3.0-3/AceConfigDialog-3.0-86/AceConfigDialog-3.0.lua"]:1852: in function `Open'
[string "@LunaUnitFrames/modules/options.lua"]:8891: in function `?'
[string "@FrameXML/ChatFrame.lua"]:4975: in function `ChatEdit_ParseText'
[string "@FrameXML/ChatFrame.lua"]:4638: in function `ChatEdit_SendText'
[string "@FrameXML/ChatFrame.lua"]:4674: in function `ChatEdit_OnEnterPressed'
[string "*ChatFrame.xml:121_OnEnterPressed"]:1: in function <[string "*ChatFrame.xml:121_OnEnterPressed"]:1>

Locals:
(*temporary) = "LunaUnitFrames isn't registed with AceConfigRegistry, unable to open config"

Please let me know if there is any more information you require on my end.

Thank you again in advance for updating the best unit frame addon, in my opinion.

**Comment by caboyd** [comment]
Hi,
I don't know how to replicat issue. Can you try again with fresh install of addon and also try backing up then deleting the LunaUnitFrames.lua file in your WTF/Account/AccountName/SavedVariables file?

**Comment by KeikakuBTG** [comment]
this is propably a wotlk config file issue. not related to release.

**Comment by Hmmintriguing** [comment]
Looks like @KeikakuBTG was correct. I was using the Wrath Luna and your version was not compatible with Wrath.

It is working now. Thanks a ton @caboyd & @KeikakuBTG
