### ISSUE TITLE
Lifebloom Error

### ISSUE THREAD

**Issue by TweedleUO** [caboyd/LunaUnitFrames-ClassicFix#22]
Message: ...aUnitFrames/libs/LibHealComm-4.0/LibHealComm-4.0.lua:819: attempt to perform arithmetic on local 'requiresLevel' (a nil value)
Time: Thu Dec  7 13:50:15 2023
Count: 13
Stack: ...aUnitFrames/libs/LibHealComm-4.0/LibHealComm-4.0.lua:819: attempt to perform arithmetic on local 'requiresLevel' (a nil value)
[string "@Interface/AddOns/LunaUnitFrames/libs/LibHealComm-4.0/LibHealComm-4.0.lua"]:819: in function <...aUnitFrames/libs/LibHealComm-4.0/LibHealComm-4.0.lua:808>
[string "@Interface/AddOns/LunaUnitFrames/libs/LibHealComm-4.0/LibHealComm-4.0.lua"]:968: in function <...aUnitFrames/libs/LibHealComm-4.0/LibHealComm-4.0.lua:966>
[string "@Interface/AddOns/LunaUnitFrames/libs/LibHealComm-4.0/LibHealComm-4.0.lua"]:2723: in function `?'
[string "@Interface/AddOns/LunaUnitFrames/libs/LibHealComm-4.0/LibHealComm-4.0.lua"]:3377: in function <...aUnitFrames/libs/LibHealComm-4.0/LibHealComm-4.0.lua:3375>

Locals: spellData = <table> {
 levels = <table> {
 }
 bomb = <table> {
 }
 coeff = 0.520000
 interval = 1
 ticks = 7
 averages = <table> {
 }
 dhCoeff = 0.343350
}
spellName = "Lifebloom"
spellID = 408124
spellRank = nil
average = nil
requiresLevel = nil
(*temporary) = <function> defined =[C]:-1
(*temporary) = 21
(*temporary) = nil
(*temporary) = "attempt to perform arithmetic on local 'requiresLevel' (a nil value)"
type = <function> defined =[C]:-1
min = <function> defined =[C]:-1
playerLevel = 21

**Comment by caboyd** [comment]
Lots of changes will need to be made to LibHealComm to support all of the new rune skills. I'll try to work on it.

**Comment by caboyd** [comment]
I added support for incoming heals for Lifebloom, Wild Growth and Penance. 
Penance is still broken because all channelling spells are broken in cast bar until blizzard fixes it.

You won't see party members heals for these spells unless they also have an updated libhealcomm with support for SOD runes.

**Comment by gustavb** [comment]
Awesome work!
