### ISSUE TITLE
dont see incoming heals (LibHealComm-4.0)

### ISSUE THREAD

**Issue by aaaror** [caboyd/LunaUnitFrames-ClassicFix#29]
On 1.15 client (SoD), I dont see incoming heals of others on me (green on HP bar).

Tried with last version (4365) of Luna Classic Fix, and also v.4362

(Shadowed unit frames show incoming heals from others correctly, so i guess its a problem of Luna Classic Fix)

More info: I created lvl 1 priest to test, and I see my own incoming heals on myself, but still dont see heals from others
So bandages and own heals work, but not incoming heals from others (i see bandages from others though)
(I do have activated incoming heals on player frame options)
Also do not see "cannibalize"

More testing: **i saw heals incoming from one friend that is using Z-perl, but not from friends using Grid2**
May this be cause they are using "**blizzard API" instead of healcomm4 on grid2**? 
How to enable heals from them if they are using blizzard API and im using luna? (if they didnt install LibHealComm-4.0)

I see that on Grid2 options u can choose "heals API" and there is an option to choose between Blizzard API and LibHealComm-4, but  i dont see this option in Luna - does luna only gets heals from LibHealComm and not Blizzard api?

![ug3N4VR](https://github.com/caboyd/LunaUI-ClassicFix/assets/130712975/314cfcb1-2210-46e6-9035-f396d053a83d)

Could an option like this be made? I think most people nowadays dont install LibHealComm (dont know if Blizzard API for heals was improved recently), so I dont see most inc heals

Also, Shadowed Unit Frames seem to "read" both Bizzard API and LibHealComm for heals (i get incoming heal from my friend using both), so is it possible to have both enabled?

**Comment by caboyd** [comment]
You are correct, there is no option yet for using blizz api for healing prediction from direct heals of others.

I am currently testing this modified version of LibHealComm that uses the blizzard APi for direct healing of others only.

https://github.com/caboyd/LibHealComm-4.0/releases/tag/SODv8-B3

**Comment by caboyd** [comment]
I can work on a toggle in Luna to filter out direct heals from others and use the blizzard api for those and still should be able to get HoTs and channel heals from libhealcomm

**Comment by aaaror** [comment]
Thanks for the fast reply, just some comments

> there is no option yet for using blizz api for healing prediction from direct heals of others

sorry if i didnt understand correctly, i may be wrong, but im testing and Shadowed Unit Frames gets prediction from heals from people that are just using Blizzard API

on the other hand, Grid2 has a selection of where to get incoming heals from (the photo i attached)

And luna chooses LibHealComm and ignores blizz api, with no option as user

Did you mean that "there is no option yet (for Luna)" or you mean in general?

>I can work on a toggle in Luna to filter out direct heals from others and use the blizzard api for those and still should be able to get HoTs and channel heals from libhealcomm

Would be very nice yea, in order to be able to see all heals disregarding what the healer/caster has installed

Currently I am using both Luna and Shadowed at the same time, just using Shadowed to get info about incoming heals (I overlaped health bars from both addons lol)


Thanks a lot for your work btw :)

**Comment by aaaror** [comment]
btw if i download the libhealcomm4.0 from the link you provided and replace if inside /libs/, should i be seeing all heals? (Even if its a work in progress atm?)
(sorry if its a newb question, im not expert at programming)

**Comment by caboyd** [comment]
New release has option to use blizzard API to get incoming heals from users without healcomm.
I didn't put it as the default so you will need to toggle it on the general options of Luna. If there are no issues then I will make it default on in next releases
https://github.com/caboyd/LunaUI-ClassicFix/releases/tag/4366
https://www.curseforge.com/wow/addons/luna-unit-frames-classic-fix/files/4958748
