### ISSUE TITLE
Temporal Beacon 

### ISSUE THREAD

**Issue by KeikakuBTG** [caboyd/LunaUnitFrames-ClassicFix#39]
"Filter Buffs" section does not count "Temporal Beacon" as a mage class buff. This might be a good thing though. You do not really want to see other players "Temporal Beacon" buffs on frames, only your own. So the best solution to this is most likely a weakaura or a relatively heavy overhaul of Luna. Consider not fixing this.

**Comment by KeikakuBTG** [comment]
i found a solution with the "Squares" section. Selecting "own buff/debuff" from the "type" menu lets me have only my own temporal beacon buff shown. IF this exact filtering is implementable to the "filter buffs" in "auras" tab, then it would be perfect.

**Comment by caboyd** [comment]
After looking into it, it appears the blizzard API is reponsible for determining if an ability is a raid buff and it doesn't include Temporal Beacon when you give it the "RAID" filter. Using the Squares will be the best option.

https://warcraft.wiki.gg/wiki/API_UnitAura
