### ISSUE TITLE
Getting an infinite return function error on targeting a unit

### ISSUE THREAD

**Issue by lvangh** [caboyd/LunaUnitFrames-ClassicFix#52]
Happens in 4373? and upwards. Had to go back to the initial fork release from a couple months ago that gives an error about distance incombat (but is dismissable so it's tolerable) because I can't target anything. 

I believe it has something to do with a custom tag? Not sure.

I am avail on Disc if needed.  
![image](https://github.com/caboyd/LunaUI-ClassicFix/assets/19690096/96119f6a-b919-4698-a4ec-d7ee2e0280b8)

**Comment by caboyd** [comment]
Thanks for report. I incorrectly fixed the range tag when they disabled range checking in combat.
Fixed in 4376
