### ISSUE TITLE
Stack Counter Size needs to be adjustable.

### ISSUE THREAD

**Issue by Marangwe** [caboyd/LunaUnitFrames-ClassicFix#54]
The stack counter on debuffs needs to be adjustable. It's the only thing that I can't make larger on the frames. It's such a tiny number on my screen compared to every other number I'm looking at. 
![image](https://github.com/caboyd/LunaUI-ClassicFix/assets/28745849/f3f43d67-4db3-4db0-9250-6eba29d45071)

ThaNKS!

**Comment by caboyd** [comment]
Finally got around to adding this. Buff Count Font Size slider will adjust the stack counter size for each frame. Buffs and debuffs use same size. It's quite a bit more work to separate them.

![image](https://github.com/user-attachments/assets/d442d02f-01a5-4c5b-be8b-05cf536d360e)
