### ISSUE TITLE
Comment here if you want WOTLK version

### ISSUE THREAD

**Issue by caboyd** [caboyd/LunaUnitFrames-ClassicFix#8]
I have not updated WOTLK version so my releases don't work for it. If three people comment here. I will update it too.

**Comment by benoakes** [comment]
I would use it for Wrath

**Comment by caboyd** [comment]
Have you noticed any issues with the old LunaUnitFrames in Wrath. I tried it and it seems to be ok for now. If it breaks I will fix it.

**Comment by Flax78** [comment]
-> i would love to have wotlk updated as well :)

**Comment by gustavb** [comment]
I would love it!
